name: cubestrap
description: "A Minecraft Launcher"

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  oauth2: ^2.0.5
  gamepads: ^0.1.9
  url_launcher: ^6.3.2
  dart_mappable: ^4.6.1
  dio: ^5.9.0
  flutter_riverpod: ^3.0.3
  riverpod_annotation: ^3.0.3
  modrinth:
    path:
      packages/modrinth
  path_provider: ^2.1.5
  flutter_dotenv: ^6.0.0
  hive_ce: ^2.16.0
  process_run: ^1.2.4


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  dart_mappable_builder: ^4.6.3
  riverpod_generator: ^3.0.3


flutter:
  uses-material-design: true
  assets:
    - .env