name: modrinth
description: "A new Flutter package project."
version: 0.0.1
homepage:
publish_to: none

environment:
  sdk: ^3.10.4
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

  dio: ^5.9.0
  dart_mappable: ^4.6.1
  
  openapi_generator_annotations: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  swagger_parser:
    path: ../swagger_parser/swagger_parser
    
  dart_mappable_builder: ^4.6.3
  build_runner: ^2.10.4
  retrofit_generator:
    path: ../retrofit/generator

dependency_overrides: 
  retrofit:
    path: ../retrofit/retrofit
  retrofit_generator:
    path: ../retrofit/generator



flutter: